# Generated by Django 5.2 on 2025-04-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='proyecto',
        ),
        migrations.RenameField(
            model_name='tarea',
            old_name='empleado',
            new_name='responsable',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='email',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='fecha_asignacion',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='fecha_vencimiento',
        ),
        migrations.AddField(
            model_name='empleado',
            name='correo',
            field=models.EmailField(default='correo@temporal.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Proyecto',
        ),
    ]
